<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Delivery.Consumer-ad35d7b5-fa53-48bd-9f9f-66f0a0ae02ce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delivery.Infraestructura\Delivery.Infraestructura.csproj" />
    <ProjectReference Include="..\Delivery.Shared\Delivery.Shared.csproj" />
  </ItemGroup>
</Project>
